logging:
  level:
    ROOT: INFO
    cn.know.act.tiny: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

management:
  health:
    elasticsearch:
      enabled: false

spring:
  profiles:
    active: dev
    include:
      - swagger
      # Uncomment to activate TLS for the dev profile
      #- tls
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/${spring.application.name};DB_CLOSE_DELAY=-1
    username: ${spring.application.name}
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    database: H2
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
      hibernate.cache.hazelcast.instance_name: ${spring.application.name}
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
    # Explicit set enable: true for combining flowable liquibase setting
    # reference: https://www.flowable.org/docs/userguide/index.html#_using_liquibase
    enabled: true
  #  data:
  #    elasticsearch:
  #      properties:
  #        classPath:
  #          home: target/elasticsearch
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard

server:
  port: 8080

proton:
  cache: # Cache configuration
    hazelcast: # Hazelcast distributed cache
      time-to-live-seconds: 3600
      backup-count: 1
      management-center: # Full reference is available at: http://docs.hazelcast.org/docs/management-center/3.9/manual/html/Deploying_and_Starting.html
        enabled: true
        update-interval: 3
        url: http://localhost:8180/hazelcast-mancenter
  # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: N2VlZjc2MTk2MjRiNDI0ZmUxYWExNjk3ZjM1YjA1OTFmYjJkNTU2YTdkODgyMDQ5NTBlMjU2M2E2ZGQxNDIwMDkzNWRiMGU0ODFiZWRjYmY2NjI4M2FlYWNiOTdkNWUxOGJjMWNmNDU2MWQzMzhlYjRlZGRmNjc3ZTFiZDc2NjA=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  metrics:
    logs: # Reports metrics in the logs
      enabled: false
      report-frequency: 60 # in seconds
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512
