const model = {
  name: {
    name: '名称',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  innerName: {
    name: '内部名称',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  description: {
    name: '描述',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  defaultRole: {
    name: '默认角色',
    type: 'BOOLEAN',
    required: false,
    readonly: false,
    unique: false,
    defaultValue: false,
  },
  permissions: {
    name: '权限',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    collection: true,
    modelType: 'SUPER',
    referenceMode: 'oneToMany',
    bidirectional: true,
    referModelAttribute: 'role',
    resourcePath: 'sys-role-permissions',
    tree: false,
    primaryKey: 'id',
    primaryKeyType: 'UUID',
    modelName: 'RolePermission',
    componentRelativePath: 'system/RolePermission',
    componentName: 'c-sys-role-permissions',
  },
  type: {
    name: '类型',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    modelType: 'ENUM',
    enumName: 'Type',
    defaultValue: 'STANDARD',
  },
  menus: {
    name: '菜单',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    collection: true,
    modelType: 'COMMON',
    referenceMode: 'manyToMany',
    bidirectional: true,
    referModelAttribute: 'roles',
    resourcePath: 'sys-menus',
    tree: true,
    primaryKey: 'id',
    primaryKeyType: 'UUID',
    modelName: 'Menu',
    componentRelativePath: 'system/Menu',
    componentName: 'c-sys-menus',
  },
  users: {
    name: '用户',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    collection: true,
    modelType: 'COMMON',
    referenceMode: 'manyToMany',
    bidirectional: true,
    referModelAttribute: 'roles',
    resourcePath: 'sys-users',
    tree: false,
    primaryKey: 'id',
    primaryKeyType: 'UUID',
    modelName: 'User',
    componentRelativePath: 'system/User',
    componentName: 'c-sys-users',
  }
}

export default model
