const model = {
  name: {
    name: '姓名',
    type: 'STRING',
    required: true,
    readonly: false,
    unique: false,
  },
  username: {
    name: '登录名',
    type: 'STRING',
    required: true,
    readonly: false,
    unique: true,
  },
  phone: {
    name: '电话',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  email: {
    name: '邮箱',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  birthday: {
    name: '生日',
    type: 'DATETIME',
    required: false,
    readonly: false,
    unique: false,
    dateType: 'DATE_ONLY'
  },
  enabled: {
    name: '可用',
    type: 'BOOLEAN',
    required: false,
    readonly: false,
    unique: false,
    defaultValue: true,
  },
  department: {
    name: '部门',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    modelType: 'COMMON',
    modelName: 'Department',
    referenceMode: 'manyToOne',
    resourcePath: 'sys-departments',
    tree: true,
    primaryKey: 'id',
    primaryKeyType: 'UUID',
    componentRelativePath: 'system/Department',
    componentName: 'c-sys-departments',
    bidirectional: false,
    arr: [],
  },
  roles: {
    name: '角色列表',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    collection: true,
    modelType: 'Role',
    referenceMode: 'manyToMany',
    bidirectional: true,
    referModelAttribute: 'users',
    resourcePath: 'sys-roles',
    tree: false,
    primaryKey: 'id',
    primaryKeyType: 'UUID',
    componentRelativePath: 'system/Role',
    componentName: 'c-sys-roles',
  },
  sex: {
    name: '性别',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    modelType: 'ENUM',
    enumName: 'Sex',
  }
}

export default model
