const model = {
  name: {
    name: '名称',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  icon: {
    name: '图标',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  title: {
    name: '标题',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  path: {
    name: '路径',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  component: {
    name: '组件',
    type: 'STRING',
    required: false,
    readonly: false,
    unique: false,
  },
  hideInBread: {
    name: '面包屑中隐藏',
    type: 'BOOLEAN',
    required: false,
    readonly: false,
    unique: false,
    defaultValue: false,
  },
  hideInMenu: {
    name: '菜单中隐藏',
    type: 'BOOLEAN',
    required: false,
    readonly: false,
    unique: false,
    defaultValue: false,
  },
  notCache: {
    name: '切换标签后不缓存',
    type: 'BOOLEAN',
    required: false,
    readonly: false,
    unique: false,
    defaultValue: false,
  },
  roles: {
    name: '角色',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    collection: true,
    modelType: 'COMMON',
    referenceMode: 'manyToMany',
    bidirectional: true,
    referModelAttribute: 'menus',
    resourcePath: 'sys-roles',
    tree: false,
    primaryKey: 'id',
    primaryKeyType: 'UUID',
    modelName: 'Role',
    componentRelativePath: 'system/Role',
    componentName: 'c-sys-roles',
  },
  _parent: {
    name: '父节点',
    type: 'MODEL',
    required: false,
    readonly: false,
    unique: false,
    modelType: 'COMMON',
    modelName: 'Menu',
    referenceMode: 'manyToOne',
    resourcePath: 'sys-menus',
    tree: true,
    primaryKey: 'id',
    primaryKeyType: 'UUID',
    componentRelativePath: 'system/Menu',
    componentName: 'c-sys-menus',
    bidirectional: false,
    arr: [],
  }
}

export default model
